services:

  flask-app:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
     DB_URL: "postgresql://test_deploy:test_deploy@db:5432/test_deploy"
    networks:
    - sync_sentry_app_network

  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: test_deploy
      POSTGRES_PASSWORD: test_deploy
      POSTGRES_DB: test_deploy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "test_deploy", "-U", "test_deploy"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sync_sentry_app_network

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - sync_sentry_app_network

volumes:
  shared:

networks:

  sync_sentry_app_network:
      name: sync_sentry_app_network
      external: true


