replicaCount: 1

image:
  repository: "deploy-test-db"
  tag: "latest"
  pullPolicy: "Never"

service:
  type: "ClusterIP"
  port: 5050

db:
  image: "postgres"
  tag: "14.5"
  username: "test_deploy"
  password: "test_deploy"
  database: "test_deploy"
  port: 5432
  pullPolicy: "IfNotPresent"
  nodePort: 30043

adminer:
  name: "adminer"
  image: "adminer"
  tag: "latest"
  port: 8080
  pullPolicy: "IfNotPresent"
  nodePort: 30080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
redis:
  name: "redis"
  image: "redis"
  tag: "7.0.0"
  port: 6379
  pullPolicy: "IfNotPresent"
  nodePort: 30079

networkName: "deployment-testing-network"

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}

imagePullSecrets: []
podSecurityContext: {}
securityContext: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /readiness
    port: http
  initialDelaySeconds: 5
  periodSeconds: 3

resources: {}
volumeMounts: []
volumes: []
nodeSelector: {}
affinity: {}
tolerations: []
nameOverride: ""
fullnameOverride: ""
ingress:
  enabled: false
  className: ""
  hosts:
    host: chart-example.local
    path: /
    pathType: ImplementationSpecific
  tls: []
  annotations: {}
serviceAccountName: ""
