apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: "adminer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "adminer"
  template:
    metadata:
      labels:
        app: "adminer"
    spec:
      containers:
        - name: {{ .Values.adminer.name }}
          image: "{{ .Values.adminer.image }}:{{ .Values.adminer.tag }}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: "adminer"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001
  selector:
    app: "adminer"
